name: my_action

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show Python version
        run: python3.9 --version

      - name: Run script
        run: python3.9 generate_new_fila.py
